name: denseRos
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - python=3.8
  - _libgcc_mutex
  - _openmp_mutex
  - addict
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - blas
  - bleach
  - bottleneck
  - brotli
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - cryptography
  - cycler
  - cython
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - flit-core
  - fontconfig
  - fonttools
  - freetype
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libgomp
  - libpng
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pathlib
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - plyfile
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pybind11
  - pycparser
  - pygments
  - pyopenssl
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtconsole-base
  - qtpy
  - readline
  - requests
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - threadpoolctl
  - tinycss2
  - tk
  - tornado
  - tqdm
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - catkin-pkg
    - deprecation
    - distro
    - docutils
    - jupyter-packaging
    - open3d
    - pyparsing
    - pyquaternion
    - rospkg
    - tomlkit
